Messages:
  Craft-No-Permission: "&cYou cannot craft this item!"
  Condensed-Error-Placing: "&cYou must place a condensed sponge in water to use it!"
  # This is the display that is shown when a player
  # has eaten a slice of sponge cake
  Time-Display:
    Time-Left: "&e%time% &aleft of sponge absorb time!"
    Condensed-Time-Left: "&e%time% &aleft of condensed sponge absorb time!"
  Command:
    No-Permission: "&cYou cannot use this command"
    Reloaded: "&aSuccessfully reloaded configuration!"

# When a condensed sponge is used it immediately breaks
Condensed-Sponge:
  # The permission a player must have to craft this
  # If the permission is empty, anyone can craft it
  Permission: "spongecakes.craft.condensed"
  # The maximum amount of blocks the condensed sponge can absorb
  Max-Absorbed: 576
  # The condensed sponge item
  Item:
    Material: "SPONGE"
    Glow: true
    Name: "&eCondensed Sponge"
    Lore:
      - "&7A condensed version of a &esponge&7."
      - "&7When placed it absorbs up to &e%max% &7blocks."
  Recipe:
    # Whether the recipe should be enabled
    Enabled: true
    # Recipe type, valid options are SHAPED or SHAPELESS
    Type: "SHAPED"
    # Represents a crafting table
    #
    # This is the shape of the recipe
    # only required if it's a SHAPED recipe.
    # MUST have the empty spaces, 3 strings in a 3x3x3 size!
    # The shape key can only be a single character, such as S!
    Shape:
      - "SSS"
      - "SSS"
      - "SSS"
    # Ingredients for the recipe.
    # If recipe is SHAPED the key such as "S"
    # must match the character above in the recipe.
    Ingredients:
      S:
        Material: "SPONGE"

Sponge-Cake:
  Permission: "spongecakes.craft.spongecake"
  # How long the player should absorb water after eating a slice
  # Time stacks when eating a slice, so eating 2 would be 20 seconds
  Absorb-Time-Per-Slice: "10s"
  # The radius of blocks to absorb, if water or waterlogged
  Absorb-Radius: 5
  Item:
    Material: "CAKE"
    Name: "&eSponge Cake"
    Lore:
      - "&eA Sponge Cake!"
      - ""
      - "&7When a slice is eaten, you gain the ability to"
      - "&7absorb nearby water in a &e%base-radius% &7block radius!"
  Recipe:
    Enabled: true
    Type: "SHAPED"
    Shape:
      - "MMM"
      - "SES"
      - "AAA"
    Ingredients:
      M:
        Material: "MILK_BUCKET"
      S:
        Material: "SUGAR"
      E:
        Material: "EGG"
      A:
        Material: "SPONGE"

Condensed-Sponge-Cake:
  Permission: "spongecakes.craft.condensedspongecake"
  Absorb-Time-Per-Slice: "30s"
  Absorb-Radius: 10
  Item:
    Material: "CAKE"
    Glow: true
    Name: "&eCondensed Sponge Cake"
    Lore:
      - "&eA Condensed Sponge Cake!"
      - ""
      - "&7When a slice is eaten, you gain the ability to"
      - "&7absorb nearby water in a &e%condensed-radius% &7block radius!"
  Recipe:
    Enabled: true
    Type: "SHAPED"
    Shape:
      - "MMM"
      - "SES"
      - "AAA"
    Ingredients:
      M:
        Material: "MILK_BUCKET"
      S:
        Material: "SUGAR"
      E:
        Material: "EGG"
      A:
        Material: "CONDENSED_SPONGE"